### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Altria002** [pai233/go-jumper#1]
![image](https://user-images.githubusercontent.com/53386594/164911432-04d14161-d190-4baa-b7ee-d7764fad6407.png)
这一步butterfly貌似没有吧，新建？

**Comment by pai233** [comment]
嗯 以后btf主题会另外出一篇教程 五一期间安排

Altria002 ***@***.***> 于 2022年4月23日周六 22:59写道：

**Comment by tonywdy** [comment]
博主，无法做跳转啊！

**Comment by pai233** [comment]
em 你那里我看了 可以跳转 但是css挂了

wdy ***@***.***> 于 2022年7月20日周三 19:00写道：

**Comment by pai233** [comment]
butterfly主题已经出了新的教程
